Repository g12-4soat/tech-lanches, pull requests merged in 2023-10, with the labels that each got.

#3 corrigindo path de pastas do dockerfile
  docker-compose.yml
Labels: bug

#11 criação de fake checkout para interface de pagamento
  src/TechLanches/TechLanches.API/Program.cs
  src/TechLanches/TechLanches.Application/IPagamentoService.cs
Labels: enhancement

#10 Create docker-build-ci.yml
  .github/workflows/docker-build-ci.yml
Labels: enhancement

#17 add middleware de erros para exceptions
  src/TechLanches/TechLanches.API/Configuration/ApplicationBuilderConfig.cs
  src/TechLanches/TechLanches.API/Program.cs
  src/TechLanches/TechLanches.Infrastructure/Middlewares/GlobalErrorHandlingMiddleware.cs
  src/TechLanches/TechLanches.Infrastructure/TechLanches.Infrastructure.csproj
Labels: enhancement

#26 Feature/fila pedidos testes
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/FilaPedidosHostedService.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/Options/WorkerOptions.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/Program.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/appsettings.Development.json
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/appsettings.json
  test/TechLanches.UnitTests/Services/FilaPedidoAggregateTest.cs
  test/TechLanches.UnitTests/TechLanches.UnitTests.csproj
  test/TechLanches.UnitTests/Worker/FilaPedidoWorkerTest.cs
Labels: enhancement

#30 Documento da entrega da fase 01
  docs/Tech Lanches.postman_collection.json
  docs/TechLanches-Local.postman_environment.json
  docs/Tech_Challenge_-_SOAT_-_FASE_1_-_G12.docx
  src/TechLanches/Adapter/Driver/TechLanches.API/Configuration/RegisterMapsConfig.cs
  src/TechLanches/Adapter/Driver/TechLanches.API/Endpoints/PedidoEndpoints.cs
  src/TechLanches/Core/TechLanches.Application/DTOs/PedidoRequestDTO.cs
  src/TechLanches/Core/TechLanches.Domain/Aggregates/Pedido.cs
Labels: documentation, enhancement

#39 revisando estrutura hexagonal e ajustes nos usings
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.SqlServer/DataSeeder.cs
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.SqlServer/EntityTypeConfigurations/ProdutoEntityTypeConfiguration.cs
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.SqlServer/Migrations/20231007023349_Cliente.Designer.cs
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.SqlServer/Migrations/20231012000206_MelhoriasClientes.Designer.cs
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.SqlServer/Migrations/TechLanchesDbContextModelSnapshot.cs
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.SqlServer/Repositories/ClienteRepository.cs
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.SqlServer/Repositories/PedidoRepository.cs
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.SqlServer/Repositories/ProdutoRepository.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Configuration/ApplicationBuilderConfig.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Configuration/DependecyInjectionConfig.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Configuration/MapEndpointsConfig.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Configuration/RegisterMapsConfig.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Configuration/SwaggerConfig.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Constantes/Constante.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Endpoints/ClienteEndpoints.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Endpoints/FilaPedidosEndpoints.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Endpoints/PedidoEndpoints.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Endpoints/ProdutoEndpoints.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Middlewares/GlobalErrorHandlingMiddleware.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Program.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Properties/launchSettings.json
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/TechLanches.Adapter.API.csproj
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/appsettings.Development.json
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/appsettings.json
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/FilaPedidosHostedService.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/Program.cs
  src/TechLanches/Core/TechLanches.Application/DTOs/PedidoRequestDTO.cs
  src/TechLanches/Core/TechLanches.Application/DTOs/ProdutoResponseDTO.cs
  src/TechLanches/Core/TechLanches.Application/Dtos/FilaPedido.cs
  src/TechLanches/Core/TechLanches.Application/Ports/Repositories/IPedidoRepository.cs
  src/TechLanches/Core/TechLanches.Application/Ports/Services/ClienteService.cs
  src/TechLanches/Core/TechLanches.Application/Ports/Services/FilaPedidoService.cs
  src/TechLanches/Core/TechLanches.Application/Ports/Services/Interfaces/IClienteService.cs
  src/TechLanches/Core/TechLanches.Application/Ports/Services/Interfaces/IFilaPedidoService.cs
  src/TechLanches/Core/TechLanches.Application/Ports/Services/Interfaces/IPagamentoService.cs
  src/TechLanches/Core/TechLanches.Application/Ports/Services/Interfaces/IPedidoService.cs
  src/TechLanches/Core/TechLanches.Application/Ports/Services/Interfaces/IProdutoService.cs
  src/TechLanches/Core/TechLanches.Application/Ports/Services/PedidoService.cs
  src/TechLanches/Core/TechLanches.Application/Ports/Services/ProdutoService.cs
  src/TechLanches/Core/TechLanches.Core/IRepository.cs
  src/TechLanches/Core/TechLanches.Domain/Aggregates/Pedido.cs
  src/TechLanches/Core/TechLanches.Domain/Aggregates/Produto.cs
  src/TechLanches/Core/TechLanches.Domain/Aggregates/Usuario.cs
  src/TechLanches/Core/TechLanches.Domain/Validations/StatusPedidoEmPreparacaoValidacao.cs
  src/TechLanches/Core/TechLanches.Domain/ValueObjects/CategoriaProduto.cs
  src/TechLanches/Core/TechLanches.Domain/ValueObjects/ItemPedido.cs
  src/TechLanches/Dockerfile.API
  src/TechLanches/TechLanches.sln
  test/TechLanches.UnitTests/Domain/PedidoAggregateTest.cs
  test/TechLanches.UnitTests/Services/FilaPedidoAggregateTest.cs
  test/TechLanches.UnitTests/Services/PedidoAggregateTest.cs
  test/TechLanches.UnitTests/Services/ProdutoAggregateTest.cs
  test/TechLanches.UnitTests/Worker/FilaPedidoWorkerTest.cs
Labels: enhancement

#51 Feature/padronizacao erros
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Endpoints/ClienteEndpoints.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Endpoints/FilaPedidosEndpoints.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Endpoints/PedidoEndpoints.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Endpoints/ProdutoEndpoints.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Middlewares/GlobalErrorHandlingMiddleware.cs
  src/TechLanches/Core/TechLanches.Application/DTOs/ErrorResponseDTO.cs
  src/TechLanches/Core/TechLanches.Domain/ValueObjects/CategoriaProduto.cs
Labels: enhancement

#56 Feature/ajustes docs
  docs/Tech_Challenge_-_SOAT_-_FASE_1_-_G12.docx
Labels: documentation, enhancement
