Repository g12-4soat/tech-lanches, pull requests merged in 2024-01, with the labels that each got.

#94 Update README.md
  README.md
Labels: documentation, enhancement

#83 arquitetura k8s e do sistema
  docs/TechLanchesArch.drawio
  docs/arquitetura-k8s.png
  docs/arquitetura-sistemica.png
  docs/diagrama-arquitetural.jpg
Labels: documentation, enhancement, help wanted

#102 ajustes na configuração do worker para rodar em kubernetes
  k8s/deployments/techlanches-worker-deployment.yaml
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/appsettings.Production.json
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/Program.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/TechLanches.Adapter.FilaPedidos.csproj
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/appsettings.Development.json
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/appsettings.Production.json
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/appsettings.json
Labels: bug

#118 Update README.md
  README.md
Labels: documentation, enhancement

#119 correção de erro do worker ao processar mensagem publicada antes de c…
  README.md
  src/TechLanches/Core/TechLanches.Application/Controllers/PedidoController.cs
  src/TechLanches/Core/TechLanches.Application/UseCases/Pedidos/PedidoUseCases.cs
  test/TechLanches.UnitTests/Services/PedidoTest.cs
Labels: bug

#120 Develop
  README.md
  src/TechLanches/Core/TechLanches.Application/Controllers/PedidoController.cs
  src/TechLanches/Core/TechLanches.Application/UseCases/Pedidos/PedidoUseCases.cs
  test/TechLanches.UnitTests/Services/PedidoTest.cs
Labels: bug, documentation, enhancement
